
version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.9.1
    ports:
      - 9200:9200  # REST API
      - 9300:9300  # Node communication
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
